// ── Tutorial action engine ──────────────────────────────────────────────────
// The behavioral half of the tutorial system. Where the existing step type
// says WHAT to highlight, actions say WHAT TO DO — open a panel, type into
// a field, click a calendar day, submit a trade.
//
// Goal: the user watches the app drive itself rather than reading tooltips.
// The existing spotlight + tooltip still draw, but on behavioral steps the
// tooltip can be a 1-line hint (or hidden entirely via step.hideTooltip).
//
// Design notes:
//   • Actions are plain data (discriminated union) — the same object graph
//     could be serialised, replayed, or generated by tests.
//   • Execution is async + sequential via an AbortController. If the user
//     advances or skips mid-sequence, the runner stops cleanly instead of
//     fighting the new step's actions.
//   • Side effects flow through TutorialSceneContext — a small interface
//     that exposes callable handles from App.tsx (setWidgetMenuOpen,
//     setDemoScript, etc.). Keeping the runner ignorant of App state lets
//     us unit-test without mounting the full tree.
//   • Nothing written here persists to localStorage. Transient trades are
//     render-time injections cleared on tour exit.

import type { Trade } from '../../types'

// ── Demo-form script ────────────────────────────────────────────────────────
// Tells AddTradeModal how to fill itself. Each field types one character at
// a time with `typeDelayMs` between keystrokes, giving a real typing feel
// without actual user input. `submitAfterMs` is the pause between the last
// keystroke and the synthetic submit — gives the user a beat to see the
// completed form before it closes.
export interface DemoFormField {
  /** Target field. The modal maps these to its internal FormData keys. */
  key:
    | 'instrument'
    | 'side'
    | 'entry'
    | 'stopLoss'
    | 'takeProfit'
    | 'result'
    | 'outcome'
    | 'setupType'
    | 'strategy'
    | 'session'
    | 'reasonForEntry'
    | 'followedRules'
    | 'emotionBefore'
    | 'emotionDuring'
    | 'didRight'
    | 'didWrong'
    | 'improve'
  /** The value to fill in. For enum fields (outcome, side, followedRules)
   *  the string is coerced to the expected type by the modal. */
  value: string
  /** Per-field override for keystroke delay. Some fields (instrument) look
   *  better typed slowly; longer notes are better batch-filled. */
  typeDelayMs?: number
  /** If set, wait this long after completing this field before starting
   *  the next — the human "pause to think" beat. Optional. */
  pauseAfterMs?: number
  /** If true, set the whole value at once instead of character-by-character.
   *  Used for longer text fields where typewriter would drag. */
  instant?: boolean
}

export interface DemoScript {
  fields: DemoFormField[]
  /** Delay between typewriter completion and auto-submit. Default 800ms. */
  submitAfterMs?: number
  /** Global keystroke delay for fields that don't override. Default 45ms. */
  typeDelayMs?: number
  /** If false, stop after the last field instead of auto-submitting. Used by
   *  the one-field-per-step tutorial so each field ends with the user
   *  clicking Next rather than the form closing itself. Default true. */
  autoSubmit?: boolean
  /** How long to wait before typing the first field. Default 380ms (the
   *  modal's open animation). Subsequent one-field scripts set this to 0
   *  so re-triggering doesn't pay the open-animation cost on every step. */
  initialDelayMs?: number
}

// ── Action union ────────────────────────────────────────────────────────────

export type TutorialAction =
  /** Idle pause — used between visible beats so the user has time to read. */
  | { type: 'wait'; ms: number }

  // Widgets ──────────────────────────────────────────────────────────────────
  | { type: 'openWidgetMenu' }
  | { type: 'closeWidgetMenu' }
  | { type: 'expandWidgetSections'; sections: Array<'small' | 'medium' | 'large'> }

  // Calendar & day panel ─────────────────────────────────────────────────────
  /** Select a calendar date. 'today' resolves against the user's timezone
   *  via the scene context. */
  | { type: 'selectDate'; date: 'today' | string }
  | { type: 'openDayPanel'; date: 'today' | string }
  | { type: 'closeDayPanel' }

  // Trade modal ──────────────────────────────────────────────────────────────
  /** Open the AddTradeModal. If `demoScript` is provided, the modal will
   *  typewriter-fill the fields and auto-submit when done. The submit
   *  flows through `safeAddTrade` so nothing is written to localStorage —
   *  instead the action engine places the submitted trade in the transient
   *  slot so it appears in the list.
   *
   *  `demoScript` may also be a `() => DemoScript` factory — the runner
   *  calls it at dispatch time, which lets scripts read live state (e.g.
   *  the currently-active checklist strategy name) instead of baking a
   *  stale value at module-load time. */
  | { type: 'openAddTrade'; demoScript?: DemoScript | (() => DemoScript) }
  | { type: 'closeAddTrade' }

  // Transient preview trade ──────────────────────────────────────────────────
  /** Inject a render-only trade into the dashboard (shown in Recent Trades
   *  and counted in stats). Never persisted. Pass null to remove. */
  | { type: 'setTransientTrade'; trade: Trade | null }

  // Checklist ────────────────────────────────────────────────────────────────
  | { type: 'addChecklistItemDemo'; text: string; afterSpacerId?: string }
  | { type: 'toggleChecklistItemDemo'; itemId: string }

  // Visual ───────────────────────────────────────────────────────────────────
  /** Briefly add a `.tutorial-pulse` class to the first matching element,
   *  removed after `ms` (default 900ms). Used to draw the eye to a just-
   *  appeared row, e.g. the fake trade that was just submitted. */
  | { type: 'pulseSelector'; selector: string; ms?: number }
  /** Smooth-scroll the first matching element into view. Used from an
   *  outgoing step's `onExit` so the incoming step's target is already
   *  positioned when the overlay re-measures — avoids a jarring double
   *  motion where the page scrolls AFTER the step index has advanced.
   *  `block` controls vertical alignment, mirroring Element.scrollIntoView.
   *  Default `center`. */
  | { type: 'scrollIntoView'; selector: string; block?: 'start' | 'center' | 'end' | 'nearest' }

  // Cleanup ──────────────────────────────────────────────────────────────────
  /** Close any tutorial-owned panels and clear the transient trade. Safe
   *  to call multiple times; used as the final step of the behavioral flow. */
  | { type: 'resetAll' }

// ── Scene context (injected by App.tsx) ─────────────────────────────────────
// These callables are thin wrappers around real app-level state setters.
// The runner treats them as opaque — it doesn't know or care how they're
// implemented, which lets us swap in mocks for tests.
export interface TutorialSceneContext {
  widgetMenu: {
    setOpen: (v: boolean) => void
    setExpandedSections: (patch: Partial<Record<'small' | 'medium' | 'large', boolean>>) => void
  }
  calendar: {
    selectDate: (date: string) => void
  }
  dayPanel: {
    open: (date: string) => void
    close: () => void
  }
  addTrade: {
    open: () => void
    close: () => void
    setDemoScript: (script: DemoScript | null) => void
  }
  transient: {
    setTrade: (trade: Trade | null) => void
  }
  checklist: {
    add: (text: string, afterSpacerId?: string) => void
    toggle: (itemId: string) => void
  }
  /** IANA timezone (e.g. "America/Los_Angeles") — lets 'today' resolve
   *  correctly across DST boundaries. Passed here so the action runner
   *  doesn't need its own date utility. */
  timezone: string
  /** Returns the local "today" as a YYYY-MM-DD string in the user's tz. */
  today: () => string
}

// ── Runner ──────────────────────────────────────────────────────────────────

/** Promise-returning sleep that resolves early if aborted. */
function sleep(ms: number, signal: AbortSignal): Promise<void> {
  return new Promise((resolve) => {
    if (signal.aborted) return resolve()
    const t = window.setTimeout(() => {
      signal.removeEventListener('abort', onAbort)
      resolve()
    }, ms)
    const onAbort = () => {
      window.clearTimeout(t)
      resolve()
    }
    signal.addEventListener('abort', onAbort, { once: true })
  })
}

/** Briefly add a class to matching elements. Idempotent and safe during abort. */
function pulse(selector: string, ms: number) {
  const el = document.querySelector(selector)
  if (!el) return
  el.classList.add('tutorial-pulse')
  window.setTimeout(() => el.classList.remove('tutorial-pulse'), ms)
}

/**
 * Execute a single action. Returns a promise that resolves when the action
 * is "done" for the purposes of the sequence — i.e. the next action can
 * start. Most actions are fire-and-forget + a small settle delay; anything
 * longer-running (typewriter form fill) is owned by its target component
 * and the runner just waits a natural beat.
 */
async function executeAction(
  action: TutorialAction,
  ctx: TutorialSceneContext,
  signal: AbortSignal,
): Promise<void> {
  if (signal.aborted) return
  switch (action.type) {
    case 'wait':
      return sleep(action.ms, signal)

    case 'openWidgetMenu':
      ctx.widgetMenu.setOpen(true)
      return sleep(220, signal) // drawer slide duration

    case 'closeWidgetMenu':
      ctx.widgetMenu.setOpen(false)
      return sleep(220, signal)

    case 'expandWidgetSections': {
      const patch: Partial<Record<'small' | 'medium' | 'large', boolean>> = {}
      for (const k of action.sections) patch[k] = true
      ctx.widgetMenu.setExpandedSections(patch)
      return sleep(180, signal)
    }

    case 'selectDate': {
      const d = action.date === 'today' ? ctx.today() : action.date
      ctx.calendar.selectDate(d)
      return sleep(120, signal)
    }

    case 'openDayPanel': {
      const d = action.date === 'today' ? ctx.today() : action.date
      ctx.dayPanel.open(d)
      return sleep(260, signal) // panel slide-in duration
    }

    case 'closeDayPanel':
      ctx.dayPanel.close()
      return sleep(220, signal)

    case 'openAddTrade': {
      // Seed BEFORE opening so the modal's `open` effect sees the script
      // on mount and starts typing immediately — no flicker of empty form.
      // Accept either a concrete DemoScript or a zero-arg factory so scripts
      // that need live store state can defer resolution to dispatch time.
      const script =
        typeof action.demoScript === 'function' ? action.demoScript() : action.demoScript
      ctx.addTrade.setDemoScript(script ?? null)
      ctx.addTrade.open()
      return sleep(260, signal)
    }

    case 'closeAddTrade':
      ctx.addTrade.close()
      ctx.addTrade.setDemoScript(null)
      return sleep(180, signal)

    case 'setTransientTrade':
      ctx.transient.setTrade(action.trade)
      return sleep(60, signal)

    case 'addChecklistItemDemo':
      ctx.checklist.add(action.text, action.afterSpacerId)
      return sleep(120, signal)

    case 'toggleChecklistItemDemo':
      ctx.checklist.toggle(action.itemId)
      return sleep(120, signal)

    case 'pulseSelector': {
      pulse(action.selector, action.ms ?? 900)
      return sleep(60, signal)
    }

    case 'scrollIntoView': {
      // Fire-and-forget smooth scroll. The subsequent `wait` action in the
      // step's action list (if any) handles timing. No sleep here — callers
      // compose scroll + wait explicitly so they can tune for distance.
      const el = document.querySelector(action.selector) as HTMLElement | null
      if (el) {
        el.scrollIntoView({ block: action.block ?? 'center', behavior: 'smooth' })
      }
      return Promise.resolve()
    }

    case 'resetAll':
      ctx.addTrade.close()
      ctx.addTrade.setDemoScript(null)
      ctx.dayPanel.close()
      ctx.widgetMenu.setOpen(false)
      ctx.transient.setTrade(null)
      return sleep(40, signal)

    default: {
      // Exhaustiveness check — TS will complain if a new variant is unhandled.
      const _exhaustive: never = action
      void _exhaustive
      return
    }
  }
}

/**
 * Run an ordered list of actions. Respects the shared abort signal — if
 * the caller aborts (e.g. the tutorial step changed), remaining actions
 * are NOT executed. Safe to call with an empty or undefined list.
 */
export async function runActions(
  actions: TutorialAction[] | undefined,
  ctx: TutorialSceneContext,
  signal: AbortSignal,
): Promise<void> {
  if (!actions || actions.length === 0) return
  for (const action of actions) {
    if (signal.aborted) return
    try {
      await executeAction(action, ctx, signal)
    } catch (err) {
      // Never let a single action throw kill the whole sequence — log
      // and keep going. Real-world: a selector might miss because the
      // target wasn't mounted yet, and we'd rather the rest of the
      // demo still play.
      // eslint-disable-next-line no-console
      console.warn('[tutorial-action] failed', action, err)
    }
  }
}
